import sprit_wave_1 from './sprit_wave_1.png';
import sprit_wave_2 from './sprit_wave_2.png';
import sprit_wave_3 from './sprit_wave_3.png';
import sprit_wave_4 from './sprit_wave_4.png';
import sprit_sad_1 from './sprit_sad_1.png';
import sprit_sad_2 from './sprit_sad_2.png';
import sprit_sad_3 from './sprit_sad_3.png';
import sprit_sad_4 from './sprit_sad_4.png';
import sprit_sad_5 from './sprit_sad_5.png';
import sprit_sad_6 from './sprit_sad_6.png';
import sprit_sad_7 from './sprit_sad_7.png';
import sprit_sad_8 from './sprit_sad_8.png';
import sprit_sad_9 from './sprit_sad_9.png';
import sprit_sad_10 from './sprit_sad_10.png';
import sprit_sad_11 from './sprit_sad_11.png';
import sprit_sad_12 from './sprit_sad_12.png';
import sprit_happy_1 from './sprit_happy_1.png';
import sprit_happy_2 from './sprit_happy_2.png';
import sprit_happy_3 from './sprit_happy_3.png';
import sprit_happy_4 from './sprit_happy_4.png';
import sprit_happy_5 from './sprit_happy_5.png';
import sprit_happy_6 from './sprit_happy_6.png';
import sprit_happy_7 from './sprit_happy_7.png';
import sprit_happy_8 from './sprit_happy_8.png';
import sprit_happy_9 from './sprit_happy_9.png';
import sprit_happy_10 from './sprit_happy_10.png';
import sprit_happy_11 from './sprit_happy_11.png';
import sprit_happy_12 from './sprit_happy_12.png';
import sprit_happy_13 from './sprit_happy_13.png';
import sprit_happy_14 from './sprit_happy_14.png';
import sprit_happy_15 from './sprit_happy_15.png';
import sprit_happy_16 from './sprit_happy_16.png';
import sprit_happy_17 from './sprit_happy_17.png';
import sprit_happy_18 from './sprit_happy_18.png';
import sprit_happy_19 from './sprit_happy_19.png';
import sprit_happy_20 from './sprit_happy_20.png';
import sprit_happy_21 from './sprit_happy_21.png';
import sprit_happy_22 from './sprit_happy_22.png';
import sprit_happy_23 from './sprit_happy_23.png';
import sprit_happy_24 from './sprit_happy_24.png';
import sprit_happy_25 from './sprit_happy_25.png';
import sprit_happy_26 from './sprit_happy_26.png';
import sprit_happy_27 from './sprit_happy_27.png';
import sprit_happy_28 from './sprit_happy_28.png';
import sprit_happy_29 from './sprit_happy_29.png';
import sprit_happy_30 from './sprit_happy_30.png';
import sprit_happy_31 from './sprit_happy_31.png';
import sprit_happy_32 from './sprit_happy_32.png';
import sprit_happy_33 from './sprit_happy_33.png';
import sprit_happy_34 from './sprit_happy_34.png';
import grid_square from './Grid_Square.png';
import up from './up_arrow.png';
import down from './down_arrow.png';
import right from './right_arrow.png';
import left from './left_arrow.png';

export const spritWaveSprites = [sprit_wave_1, sprit_wave_2, sprit_wave_3, sprit_wave_4];
export const spritSadSprites = [sprit_sad_1, sprit_sad_2, sprit_sad_3, sprit_sad_4, sprit_sad_5, sprit_sad_6, sprit_sad_7, sprit_sad_8, sprit_sad_9, sprit_sad_10, sprit_sad_11, sprit_sad_12];
export const spritHappySprites = [sprit_happy_1, sprit_happy_2, sprit_happy_3, sprit_happy_4, sprit_happy_5, sprit_happy_6, sprit_happy_7, sprit_happy_8, sprit_happy_9, sprit_happy_10, sprit_happy_11, sprit_happy_12, sprit_happy_13, sprit_happy_14, sprit_happy_15, sprit_happy_16, sprit_happy_17, sprit_happy_18, sprit_happy_19, sprit_happy_20, sprit_happy_21, sprit_happy_22, sprit_happy_23, sprit_happy_24, sprit_happy_25, sprit_happy_26, sprit_happy_27, sprit_happy_28, sprit_happy_29, sprit_happy_30, sprit_happy_31, sprit_happy_32, sprit_happy_33, sprit_happy_34];
export const gridSquare = [grid_square];
export const arrows = {up, down, left, right};